version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db-test-java2-test
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
      TZ: Asia/Ho_Chi_Minh
      PGTZ: UTC
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: